"""Add email column

Revision ID: 587a6c263cf0
Revises: 
Create Date: 2024-11-11 08:28:02.411980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587a6c263cf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserTable', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'UserTable', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserTable', type_='unique')
    op.drop_column('UserTable', 'email')
    # ### end Alembic commands ###
